Data visualization
OfficeDev/microsoft-teams-ui-component-library pull request #52
Opened 2021-02-11 23:21 UTC by akatrukhin

## [Open in Storybook ↗️](https://dev-int.teams.microsoft.com/storybook/bar-chart/index.html?path=/story/ui-templates-dashboards--with-data-vizualization)

## Specs in Figma
• [HVC Data Vizualization ↗️](https://www.figma.com/file/gF7qOLyLksVslHGNqQR2Jj/?node-id=2237%3A0)

Line chart
Line Area chart
Line Stacked chart
Bar chart
Stacked bar chart
Horizontal bar chart
Grouped bar chart
Horizontal stacked bar chart
Pie chart
Doughnut  chart

![Screen Shot 2021-02-11 at 3 20 18 PM](https://user-images.githubusercontent.com/21069453/107711565-b8605e80-6c7c-11eb-9021-50e2c956fa84.png)
![Screen Shot 2021-02-11 at 3 19 46 PM](https://user-images.githubusercontent.com/21069453/107711574-bc8c7c00-6c7c-11eb-9a8c-30cecde664cf.png)

2021-03-09 22:42 UTC, asnow003 approved these changes

2021-03-09 23:29 UTC, thure requested changes
Looks like there are just a few naming / API issues related to the Board component that need adjustment.

2021-03-09 23:29 UTC, thure commented on src/stories/Taskboard.stories.tsx
> +import { ThemeProvider } from "../lib/withTheme";
Change to import `withTheme` from `src`, since `lib` is built.

2021-03-09 23:29 UTC, thure commented on src/stories/Taskboard.stories.tsx
> +import Taskboard from "../components/Taskboard";
Use the `Board` component. There is no such component as `Taskboard`.

2021-03-09 23:29 UTC, thure commented on src/stories/Taskboard.stories.tsx
> +    tasks: [
The `Board` component expects `items`.

2021-03-10 19:26 UTC, thure approved these changes
LGTM!

2021-03-10 19:53 UTC, merged